Trying to test workflow breaking

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -36,4 +36,6 @@ jobs:
       - name: Build
         run: npm run build
 
-      ##Added Github actions maybe working now
+      # 🚨 Temporary step to force failure
+      - name: Force failure
+        run: exit 1
